#!/bin/bash
#methodology/ms/fin/fdepth/methodology.md
#methodology/ms/fin/fstabl/methodology.md
#methodology/ms/fin/pubacc/methodology.md
#methodology/ms/neq/ginipt/methodology.md
#methodology/ms/neq/ishrat/methodology.md
#methodology/ms/tax/crptax/methodology.md
#methodology/ms/tax/taxprg/methodology.md
#methodology/ms/tax/taxrev/methodology.md
#methodology/ms/wen/colbar/methodology.md
#methodology/ms/wen/employ/methodology.md
#methodology/ms/wwb/fatinj/methodology.md
#methodology/ms/wwb/matern/methodology.md
#methodology/ms/wwb/senior/methodology.md
#methodology/ms/wwb/unempl/methodology.md
#methodology/pg/edu/enrpri/methodology.md
#methodology/pg/edu/enrsec/methodology.md
#methodology/pg/edu/puptch/methodology.md
#methodology/pg/edu/yrsedu/methodology.md
#methodology/pg/glb/armexp/methodology.md
#methodology/pg/glb/foraid/methodology.md
#methodology/pg/glb/milexp/methodology.md
#methodology/pg/glb/rdfund/methodology.md
#methodology/pg/hlc/atbrth/methodology.md
#methodology/pg/hlc/cstunt/methodology.md
#methodology/pg/hlc/dptcov/methodology.md
#methodology/pg/hlc/fampln/methodology.md
#methodology/pg/hlc/physpc/methodology.md
#methodology/pg/inf/aqelec/methodology.md
#methodology/pg/inf/drkwat/methodology.md
#methodology/pg/inf/intrnt/methodology.md
#methodology/pg/inf/sansrv/methodology.md
#methodology/pg/inf/trnetw/methodology.md
#methodology/pg/rts/edemoc/methodology.md
#methodology/pg/rts/gendeq/methodology.md
#methodology/pg/rts/pubsrv/methodology.md
#methodology/pg/rts/rulelw/methodology.md
#methodology/pg/rts/unconv/methodology.md
#methodology/pg/saf/cybsec/methodology.md
#methodology/pg/saf/murder/methodology.md
#methodology/pg/saf/prison/methodology.md
#methodology/pg/saf/secapp/methodology.md
#methodology/sus/eco/biodiv/methodology.md
#methodology/sus/eco/redlst/methodology.md
#methodology/sus/ghg/beefmk/methodology.md
#methodology/sus/ghg/coalpw/methodology.md
#methodology/sus/ghg/gtrans/methodology.md
#methodology/sus/lnd/carbon/methodology.md
#methodology/sus/lnd/chmpol/methodology.md
#methodology/sus/lnd/defrst/methodology.md
#methodology/sus/lnd/nitrog/methodology.md
#methodology/sus/lnd/watman/methodology.md
#methodology/sus/nrg/airpol/methodology.md
#methodology/sus/nrg/altnrg/methodology.md
#methodology/sus/nrg/nrgint/methodology.md
#methodology/sus/wst/mswgen/methodology.md
#methodology/sus/wst/recycl/methodology.md

mkdir -p datasets
mkdir -p datasets/credit/
mkdir -p datasets/dposit/
mkdir -p datasets/bfifty/
mkdir -p datasets/topten/
mkdir -p datasets/povnrt/
mkdir -p datasets/yrsrtm/
mkdir -p datasets/yrsrtw/
mkdir -p datasets/gdpmkt/
mkdir -p datasets/populn/
mkdir -p datasets/tonrec/
mkdir -p datasets/totdon/
mkdir -p datasets/edurdp/
mkdir -p datasets/gvtrdp/
mkdir -p datasets/nrsrch/
mkdir -p datasets/avelec/
mkdir -p datasets/quelec/
mkdir -p datasets/avintr/
mkdir -p datasets/quintr/
mkdir -p datasets/railnt/
mkdir -p datasets/roadnt/
mkdir -p datasets/wmfnmn/
mkdir -p datasets/wmmarr/
mkdir -p datasets/wmmobl/
mkdir -p datasets/wmplmt/
mkdir -p datasets/populn/
mkdir -p datasets/pripop/
mkdir -p datasets/frshwt/
mkdir -p datasets/marine/
mkdir -p datasets/terrst/
mkdir -p datasets/bfcons/
mkdir -p datasets/bfprod/
mkdir -p datasets/populn/
mkdir -p datasets/tco2em/
mkdir -p datasets/crbnav/
mkdir -p datasets/crbnlv/
mkdir -p datasets/basela/
mkdir -p datasets/montrl/
mkdir -p datasets/stkhlm/
mkdir -p datasets/frstav/
mkdir -p datasets/frstlv/
mkdir -p datasets/cwueff/
mkdir -p datasets/wtstrs/
mkdir -p datasets/biowas/
mkdir -p datasets/fsloil/
mkdir -p datasets/geopwr/
mkdir -p datasets/hydrop/
mkdir -p datasets/natgas/
mkdir -p datasets/nclear/
mkdir -p datasets/tlcoal/

mv methodology/ms/fin/fdepth/credit/methodology.md datasets/credit/methodology.md
mv methodology/ms/fin/fdepth/dposit/methodology.md datasets/dposit/methodology.md
mv methodology/ms/neq/ishrat/bfifty/methodology.md datasets/bfifty/methodology.md
mv methodology/ms/neq/ishrat/topten/methodology.md datasets/topten/methodology.md
mv methodology/ms/wwb/senior/povnrt/methodology.md datasets/povnrt/methodology.md
mv methodology/ms/wwb/senior/yrsrtm/methodology.md datasets/yrsrtm/methodology.md
mv methodology/ms/wwb/senior/yrsrtw/methodology.md datasets/yrsrtw/methodology.md
mv methodology/pg/glb/foraid/gdpmkt/methodology.md datasets/gdpmkt/methodology.md
mv methodology/pg/glb/foraid/populn/methodology.md datasets/populn/methodology.md
mv methodology/pg/glb/foraid/tonrec/methodology.md datasets/tonrec/methodology.md
mv methodology/pg/glb/foraid/totdon/methodology.md datasets/totdon/methodology.md
mv methodology/pg/glb/rdfund/edurdp/methodology.md datasets/edurdp/methodology.md
mv methodology/pg/glb/rdfund/gvtrdp/methodology.md datasets/gvtrdp/methodology.md
mv methodology/pg/glb/rdfund/nrsrch/methodology.md datasets/nrsrch/methodology.md
mv methodology/pg/inf/aqelec/avelec/methodology.md datasets/avelec/methodology.md
mv methodology/pg/inf/aqelec/quelec/methodology.md datasets/quelec/methodology.md
mv methodology/pg/inf/intrnt/avintr/methodology.md datasets/avintr/methodology.md
mv methodology/pg/inf/intrnt/quintr/methodology.md datasets/quintr/methodology.md
mv methodology/pg/inf/trnetw/railnt/methodology.md datasets/railnt/methodology.md
mv methodology/pg/inf/trnetw/roadnt/methodology.md datasets/roadnt/methodology.md
mv methodology/pg/rts/gendeq/wmfnmn/methodology.md datasets/wmfnmn/methodology.md
mv methodology/pg/rts/gendeq/wmmarr/methodology.md datasets/wmmarr/methodology.md
mv methodology/pg/rts/gendeq/wmmobl/methodology.md datasets/wmmobl/methodology.md
mv methodology/pg/rts/gendeq/wmplmt/methodology.md datasets/wmplmt/methodology.md
mv methodology/pg/saf/prison/populn/methodology.md datasets/populn/methodology.md
mv methodology/pg/saf/prison/pripop/methodology.md datasets/pripop/methodology.md
mv methodology/sus/eco/biodiv/frshwt/methodology.md datasets/frshwt/methodology.md
mv methodology/sus/eco/biodiv/marine/methodology.md datasets/marine/methodology.md
mv methodology/sus/eco/biodiv/terrst/methodology.md datasets/terrst/methodology.md
mv methodology/sus/ghg/beefmk/bfcons/methodology.md datasets/bfcons/methodology.md
mv methodology/sus/ghg/beefmk/bfprod/methodology.md datasets/bfprod/methodology.md
mv methodology/sus/ghg/gtrans/populn/methodology.md datasets/populn/methodology.md
mv methodology/sus/ghg/gtrans/tco2em/methodology.md datasets/tco2em/methodology.md
mv methodology/sus/lnd/carbon/crbnav/methodology.md datasets/crbnav/methodology.md
mv methodology/sus/lnd/carbon/crbnlv/methodology.md datasets/crbnlv/methodology.md
mv methodology/sus/lnd/chmpol/basela/methodology.md datasets/basela/methodology.md
mv methodology/sus/lnd/chmpol/montrl/methodology.md datasets/montrl/methodology.md
mv methodology/sus/lnd/chmpol/stkhlm/methodology.md datasets/stkhlm/methodology.md
mv methodology/sus/lnd/defrst/frstav/methodology.md datasets/frstav/methodology.md
mv methodology/sus/lnd/defrst/frstlv/methodology.md datasets/frstlv/methodology.md
mv methodology/sus/lnd/watman/cwueff/methodology.md datasets/cwueff/methodology.md
mv methodology/sus/lnd/watman/wtstrs/methodology.md datasets/wtstrs/methodology.md
mv methodology/sus/nrg/altnrg/biowas/methodology.md datasets/biowas/methodology.md
mv methodology/sus/nrg/altnrg/fsloil/methodology.md datasets/fsloil/methodology.md
mv methodology/sus/nrg/altnrg/geopwr/methodology.md datasets/geopwr/methodology.md
mv methodology/sus/nrg/altnrg/hydrop/methodology.md datasets/hydrop/methodology.md
mv methodology/sus/nrg/altnrg/natgas/methodology.md datasets/natgas/methodology.md
mv methodology/sus/nrg/altnrg/nclear/methodology.md datasets/nclear/methodology.md
mv methodology/sus/nrg/altnrg/tlcoal/methodology.md datasets/tlcoal/methodology.md
