#!/bin/bash
SSPI_DATA_WEBAPP=$(dirname $(dirname "$(realpath "$0")"))
echo "SSPI_DATA_WEBAPP: $SSPI_DATA_WEBAPP"
FILELIST=$(fd methodology.md "$SSPI_DATA_WEBAPP/methodology")
for file in $FILELIST; do
    SSPI_ITEM_CODE=$(echo "$file" | xargs dirname | sed 's/.*\///')
    echo "$SSPI_ITEM_CODE"
    if [[ $SSPI_ITEM_CODE == methodology ]]; then
        SSPI_ITEM_CODE="sspi"
    fi
    SSPI_METHODOLOGY_FRONTMATTER=$(sspi metadata item "$SSPI_ITEM_CODE" | yq --yaml-output | sed '1i---' | sed '$a---')
    sed -i '/^---$/,/^---$/d' "$file"
    FILE_CONTENTS=$(cat "$file")
    echo "$SSPI_METHODOLOGY_FRONTMATTER" > "$file"
    echo "$FILE_CONTENTS" >> "$file"
done
