from sys import path
path.append("../")

from database_connector.SSPIDatabaseConnector import SSPIDatabaseConnector

sspi_database = SSPIDatabaseConnector()
res = sspi_database.get_data_local("auth/whoami")
print(res.text)
# sspi_database.get_data_local("/api/v1/collect/BIODIV")
# sspi_database.get_data_local("/api/v1/collect/REDLST")
# sspi_database.get_data_local("/api/v1/collect/NITROG")
# sspi_database.get_data_local("/api/v1/collect/WATMAN")
# sspi_database.get_data_local("/api/v1/collect/STKHLM")
# sspi_database.get_data_local("/api/v1/collect/NRGINT")
# sspi_database.get_data_local("/api/v1/collect/AIRPOL")
# sspi_database.get_data_local("/api/v1/collect/ALTNRG")
# sspi_database.get_data_local("/api/v1/collect/COALPW")
# sspi_database.get_data_local("/api/v1/collect/GTRANS")
# sspi_database.get_data_local("/api/v1/collect/LFPART")
# sspi_database.get_data_local("/api/v1/collect/COLBAR")
# sspi_database.get_data_local("/api/v1/collect/CHILDW")
# sspi_database.get_data_local("/api/v1/collect/SENIOR")
# sspi_database.get_data_local("/api/v1/collect/UNEMPL")
# sspi_database.get_data_local("/api/v1/collect/FATINJ")
# sspi_database.get_data_local("/api/v1/collect/TAXREV")
# sspi_database.get_data_local("/api/v1/collect/FDEPTH")
# sspi_database.get_data_local("/api/v1/collect/GINIPT")
# sspi_database.get_data_local("/api/v1/collect/PUPTCH")
# sspi_database.get_data_local("/api/v1/collect/ATBRTH")
# sspi_database.get_data_local("/api/v1/collect/DPTCOV")
# sspi_database.get_data_local("/api/v1/collect/PHYSPC")
# sspi_database.get_data_local("/api/v1/collect/FAMPLN")
# sspi_database.get_data_local("/api/v1/collect/CSTUNT")
# sspi_database.get_data_local("/api/v1/collect/DRKWAT")
# sspi_database.get_data_local("/api/v1/collect/SANSRV")
# sspi_database.get_data_local("/api/v1/collect/INTRNT")
# sspi_database.get_data_local("/api/v1/collect/PRISON")
# sspi_database.get_data_local("/api/v1/collect/RDFUND")
# sspi_database.get_data_local("/api/v1/collect/UNPOPL")
# sspi_database.get_data_local("/api/v1/collect/GDPMEK")
# sspi_database.get_data_local("/api/v1/collect/GDPPPP")
