#!/bin/bash
cat << EOF >| wsgi.py
from sspi_flask_app import init_app
from config import DevConfig

app = init_app(DevConfig)
if __name__ == "__main__":
    app.run(host='127.0.0.1', port=5000)
EOF
echo SECRET_KEY='thiscanbewhateveryouwantfordevelopment' > .env 
mkdir -p instance && touch instance/database.db
echo SQLALCHEMY_DATABASE_URI=\"sqlite:///$(pwd)/instance/database.db\" >> .env 
type python && SSPI_PYTHON=python || SSPI_PYTHON=python3
$SSPI_PYTHON -m venv env
source env/bin/activate && pip install -r requirements.txt
pip install -e .
